<a href="https://colab.research.google.com/github/hamidrezanorouzi/numericalMethods/blob/main/Lectures/Lecture04_linear_systems_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **System of Linear Equations - Part 1**

&nbsp;

Lecturer: **Hamidreza Norouzi**

&nbsp;

### **Notes**❕
This content forms a part of the instructional presentations for the **`numerical methods in chemical engineering`** course designed for undergraduate chemical engineering students at Amirkabir University of Technology.

Feel free to utilize the information and source codes provided in this material, ensuring appropriate acknowledgment of the original document.

The visual elements featured in this document are either original or have been obtained from the following sources, unless specified otherwise:

* Steven C. Chapra, Applied Numerical Methods with Matlab for Engineers and Scientists, 3rd edition, McGraw-Hill (2012).
* Amos Gilat and Vish Subramanian, Numerical Methods for Engineers and Scientists, 3rd edition, Wiley (2014).

<div align="center">
🟧 🟧 🟧
</dive>

---

# 🔴 1) Where do we face solving a set of linear equations?

* **Chemical Systems (Tens to Thousands of Equations):** M&E balances are employed in diverse chemical systems such as distillation columns, adsorption columns, and chemical processes. These systems often entail solving systems of equations ranging from tens to thousands, reflecting the intricate interplay of chemical reactions and mass/energy transfers.

* **Reactor Engineering (Tens of Equations):** Reactor engineering deals with systems characterized by numerous elementary reactions. Typically, tens of equations are formulated to describe reaction kinetics and species concentrations within the reactor.

* **Curve Fitting (Usually Less than 10 Equations):** Curve fitting scenarios involve the determination of linear systems, typically containing fewer than ten equations. These are essential for fitting experimental data to mathematical models or functions.

* **Solving ODEs and PDEs (Thousands to Millions of Equations):** Solving ordinary differential equations (ODEs) and partial differential equations (PDEs), often encountered in boundary value problems, necessitates techniques like linearization and discretization. These processes transform complex continuous problems into sets of linear equations that may range from thousands to millions in scale.


# 🔵 2) Cramer's rule
* It is best suited for small systems, typically a set with  2 to 4 equations.


\begin{cases}
a_{1,1}x_1 + a_{1,2}x_2 + ... + a_{1,n}x_n = b_1 \\
a_{2,1}x_1 + a_{2,2}x_2 + ... + a_{2,n}x_n = b_2 \\
. \\
. \\
. \\
a_{n,1}x_1 + a_{n,2}x_2 + ... + a_{n,n}x_n = b_n \\
\end{cases}

* In matrix form it is:
$$
[A]\{x\}=\{B\}
$$


* The solution to the above set is given by:
$$
x_1 = \frac{D_1}{D}, x_2=\frac{D_2}{D}, ..., x_n = \frac{D_n}{D}  \tag{2-1}
$$

&nbsp;

\begin{align}
D_1 &=
\begin{vmatrix}
b_{1} & a_{1,2} & ... & a_{1,n} \\
b_{2} & a_{2,2} & ... & a_{2,n} \\
. \\ . \\ . \\
b_{n} & a_{n,2} & ... & a_{n,n}
\end{vmatrix} \notag
&,
D_n =
\begin{vmatrix}
a_{1,1} & a_{1,2} & ... & b_{1} \\
a_{2,1} & a_{2,2} & ... & b_{2} \\
. \\ . \\ . \\
a_{n,1} & a_{n,2} & ... & b_{n}
\end{vmatrix} \tag{2-2}
&&
\end{align}


\begin{align}
D &=
\begin{vmatrix}
a_{1,1} & a_{1,2} & ... & a_{1,n} \\
a_{2,1} & a_{2,2} & ... & a_{2,n} \\
. \\ . \\ . \\
a_{n,1} & a_{n,2} & ... & a_{n,n}
\end{vmatrix} \tag{2-3}
&&
\end{align}

## Arithmetic operations in Cramer's rule
* When the number of equations increases, the required operations grow exponentially and the Cramer's rule becomes infeasible.

| No. equations | No. determinantes | No. multiplication | Total operations|
|:---|:---:|:---:|:---:|
|2   | 3 | 2 | 6|
|3 | 4 | 12 | 48 |
|n | n+1 | (n-1)n! | (n+1)(n-1)n!|

# 🟢 3) Gauss elimination

## 3-1) Gauss elimination without pivoting

* Consider the following set of equations:
$$
[A]\{x\} = \{B\}
$$
 where $[A]$ is the matrix of coefficient and $\{B\}$ is the vector of known variables and $\{x\}$ is the vector of unknowns.
* Gauss elimination is based on the operations (on rows of the system) to convert the coefficient matrix into a upper-triangle matrix:
$$
[U]\{x\} = \{B^{'}\}
$$

* Then using back-substitution from the last equation to obtain the solution of the system.

<div align="center">
<img src="https://drive.google.com/uc?id=1f2csAYPmDogI2vuas9KbmJ7JOyo6GcHq" width = "400">
</div>

### Rules of for triangulation:

* Any equation can be multiplied by a nonzero scalar without affecting the solution.
* Any equation can be added to (or subtracted from) another equation without affecting the solution.
* Any two equations can interchange positions within the set without affecting the solution.


### ❓ **Example 1:**
Solve the following system of equations using gauss elimination.

\begin{cases}
3x_1 +18 x_2+ 9x_3= 18\\
2x_1 +3 x_2 +3 x_3=117\\
4x_1 +1 x_2 +2 x_3=283
\end{cases}

&nbsp;


💡 *Solution*


The above set in matrix form becomes:
$$ \begin{bmatrix}
3 & 18 & 9 \\
2 & 3 & 3 \\
4 & 1 & 2
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3\end{bmatrix} =
\begin{bmatrix} 18 \\ 117\\ 283 \end{bmatrix}
$$

**Step 1:** Write the augmented matrix:


\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
2 & 3 & 3 & 117 \\
4 & 1 & 2 & 283 \\
\end{array}

**Step 2:** $a_{1,1}$ is chosen as pivot element to make elements under the pivot element zero:

1) Row2 - (2/3) * Row1 → Row2

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
4 & 1 & 2 & 283 \\
\end{array}

2) Row3 - (4/3) * Row1 → Row3

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
0 & -23 & -10 & 259 \\
\end{array}



**Step 3:** $a_{2,2}$ is chosen as pivot element to make elements under the pivot element zero:

1) Row3 - (23/7) * Row2 → Row3

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
0 &  0 & \frac{-7}{3} & \frac{-28}{3} \\
\end{array}



**Step 4:** Back substitution:

&nbsp;

\begin{cases}
3x_1+18x_2+9x_3 = 18 \\
-9x_2 - 3x_3 = 105 \\
-\frac{7}{3}x_3 = \frac{-28}{3}
\end{cases}

&nbsp;


$$
x_3 = 4,  x_2 = -13, x_1 = 117
$$

## 3-2) Code for Gauss elimination without pivoting

In [1]:
import numpy as np

def gaussEliminationNoPivoting(A, B):

  n = len(A)
  augMat = np.concatenate([A,B],1)

  # forward pass
  for k in range(n-1):

    # making elements below the pivot element zero
    for m in range(k+1,n):
      augMat[m,:] -= (augMat[m,k]/augMat[k,k]) * augMat[k,:]

  # back substitution
  x = np.zeros((n,1))
  x[n-1] = augMat[n-1,n]/augMat[n-1,n-1]

  for k in range(n-2, -1, -1):
    x[k] = (augMat[k,n] - np.dot(augMat[k,k+1:n],x[k+1:n]) )/augMat[k,k]

  return x

In [2]:
A = np.array([[3.0, 18 , 9],[2,3,3],[4,1,2]]);
B = np.array([[18, 117, 283]]).T

x = gaussEliminationNoPivoting(A,B)
print(x)

[[ 72.]
 [-13.]
 [  4.]]


## 3-3) Gauss elimination with partial pivoting
* Consider the following system of equations:
  
\begin{cases}
2x_2 + 5x_3 = 10\\
x_1+ 3x_2 - x_3 = 4\\
3x_1+x_2+x_3 = -2
\end{cases}

* This will give the following form:

$$ \begin{bmatrix}
0 & 2 & 5 \\
1 & 3 & -1 \\
3 & 1 & 1
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3\end{bmatrix} =
\begin{bmatrix} 10 \\ 4\\ -2 \end{bmatrix}
$$


* In each step, before eliminating the elements below the pivot element, it is advantageous to determine the coefficient with the **largest absolute value** in the column **below the pivot element**. The rows can then be **switched** so that the largest element is the pivot element.

* By rearranging rows of the augmented matrix, we can obtain a diagonal dominant matrix (partial pivoting).

 * This reduces the possibility of division by zero.

 * Increases the accuracy of calculation by dividing the elements by larger values (decreasing round-off error).


* Lets consider the following system of two equations. The exact solution is $x_1 = 1/3$ and $x_2 = 2/3$
\begin{cases}
3.0\times10^{-12}x_1 + 3x_2 = 1 \\
2.000000000001x_1 + x_2 = 1
\end{cases}
* Now, lets test the solution of Gauss elemination without pivoting:

In [3]:
A = np.array([[3.0e-12, 3.0],[1.0,1.0]]);
B = np.array([[2.000000000001, 1]]).T

x = gaussEliminationNoPivoting(A,B)
print("Answer is \n",x)

Answer is 
 [[0.33336297]
 [0.66666667]]


## 3-4) Code for Gauss elimination with pivoting


In [4]:
import numpy as np

def gaussElimination(A, B):
  tol = 0.000001
  #number of rows and columns
  nr,nc = A.shape;
  if nr!=nc:
    print('input matrix A is not square!')
    return None

  #number of equations in the set
  n,m = B.shape
  if n!= nr:
    print('A and B size mismatch')
    return None

  Aug = np.concatenate([A,B],1);
  detA = 1;

  #main loop
  for k in range(n-1):

    #first: partial pivoting
    pRow = np.argmax(abs(Aug[k:, k])) + k

    #interchanges the rows, if necessary
    if pRow != k:
      temp = np.array(Aug[k,:])
      Aug[k,:] = Aug[pRow,:]
      Aug[pRow,:] = temp
      detA = -detA  #change of sign


    if abs(Aug[k,k]) < tol:
      print('Singular matrix!')
      return None


    # making elements below the pivot element zero
    for m in range(k+1,n):
      Aug[m,:] -= Aug[m,k]/Aug[k,k] * Aug[k,:]

  #the last equation never checked
  if abs(Aug[n-1,n-1]) < tol:
    print('Singular matrix!')
    return None

  # back substitution
  x = np.zeros((n,1))
  x[n-1] = Aug[n-1,n]/Aug[n-1,n-1];
  detA = detA*Aug[n-1,n-1];

  for k in range(n-2, -1, -1):
    x[k] = (Aug[k,n] - np.dot(Aug[k,k+1:n],x[k+1:n]) )/Aug[k,k]
    detA = detA * Aug[k,k]

  return x, detA;

In [5]:
A = np.array([[3.0e-12, 3.0],[1.0,1.0]]);
B = np.array([[2.00000000001, 1]]).T

x, det = gaussElimination(A,B)
print("Answer is \n",x)

Answer is 
 [[0.33333333]
 [0.66666667]]


## 3-5) Determinant evaluation with Gauss elimination
* The determinant of a **triangular matrix** can be simply computed as the product of its diagonal elements:

$$
D = a_{1,1}.a_{2,2}.a_{3,3} . . . a_{n,n} \tag{3-1}
$$

* If the programs uses **partial pivoting** for obtaining the triangular  matrix, the sign of the determinant switches with every row interchange. So, Eq. (3-1) should be changed to:

$$
D = a_{1,1}.a_{2,2}.a_{3,3} . . . a_{n,n}(-1)^p \tag{3-2}
$$
 where $p$ is the number of times that rows are interchanged/pivoted.

## 4) Tridiagonal systems
* Some chemical engineering problems lead to a set of equations whose most of its elements in the coefficient matrix is zero: sparse matrix.
* If nonzero elements are clustered about the diagonal elements, the matrix is called banded. As an example, the following matrix is tri-diagonal matrix.

<div align="center">
<img src="https://drive.google.com/uc?id=1plVWLLmIAOiFkV7iuTBiqQ_wQ52ctQOt" width="500">
</div>

* Memory requirement:
 * Consider $n×n$ matrix, Gauss elimination requires $n^2$ elements to store the values of the coefficients.

 * But with the tri-diagonal notation it only requires to save $e_i$,  $f_i$ and $g_i$, each has $(n-1) + n + (n-1)$ elements $→ 3n-2$ elements in total.
* Arithmetic operations:
 * Applying Gauss elimination method requires $O(n^3)$ operations [explained in section 9.2.2] while tri-diagonal method only requires $O(n)$ operations.

## ❓ **Example 2**
Solve the following tri-diagonal system using Gauss elimination.

$$ \begin{bmatrix}
2.04 & -1 & 0 & 0 \\
-1 & 2.04 & -1& 0 \\
0 & -1 & 2.04& -1 \\
0 & 0 & -1 & 2.04 \\
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{bmatrix} =
\begin{bmatrix} 40.8 \\ 0.8\\ 0.8 \\ 200.8 \end{bmatrix}
$$

💡 *solution*

1) Similar to Gauss elimination, we start zeroing the elements under each pivot element.
$$
f_2 = f_2 - \frac{e_2}{f_1}g_1 = 2.04 - \frac{-1}{2.04}(-1)=1.55 \\
r_2 = r_2 - \frac{e_2}{f_1}r_1 = 0.8 - \frac{-1}{2.04}(40.8) = 20.8
$$
2) Notice that $g_2$ is unmodified, since the elemenet above it is zero.

3) Perforoming a similar calculation will result the following system:

$$ \begin{bmatrix}
2.04 & -1 & 0 & 0 \\
0 & 1.550 & -1& 0 \\
0 & 0 & 1.395& -1 \\
0 & 0 & 0 & 1.323 \\
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{bmatrix} =
\begin{bmatrix} 40.8 \\ 20.8\\ 14.221 \\ 210.996 \end{bmatrix}
$$

4) Back substitution:


\begin{aligned}
&x_4 = \frac{r_4}{f_4} = \frac{210.996}{1.323} =159.480 \\
&x_3= \frac{r_3-g_3x_4}{f_3} = \frac{14.221-(-1)159.480}{1.395} = 124.538 \\
&x_2= \frac{r_2-g_2x_3}{f_2} = \frac{20.800-(-1)124.538}{1.550} = 93.778 \\
&x_1= \frac{r_1-g_1x_2}{f_1} = \frac{80.800-(-1)93.778}{2.04} = 65.970\\
\end{aligned}


### General formula for Tri-diagonal system
* It is called **Thomas** algorithm and consists of two steps:
 * Forward swip:
 $$
 \begin{aligned}
 g^{'}_i &=
 \begin{cases}  
 \frac{g_i}{f_i} & i=1 \\ \frac{g_i}{f_i-e_i g^{'}_{i-1}} & i=2,3,...,n-1
 \end{cases} \notag
 \\
 r^{'}_i &=
 \begin{cases}
 \frac{r_i}{f_i} & i=1 \\
 \frac{r_i-e_i r^{'}_{i-1}}{f_i-e_i g^{'}_{i-1}} & i=2,3,...,n
 \end{cases}
 \end{aligned}
 $$

 * Back substitution:
  
  $$
  \begin{aligned}
  x_n &= r^{'}_n \\
  x_i &= r^{'}_i - g^{'}_i x_{i+1} \ \ \ \  \text{for} \ \ \ i= n-1, n-2, ..., 1
  \end{aligned}
  $$

In [6]:
import numpy as np

def triDiagonal(e, f, g, r):

    #number of equations in the set
    n = len(f);

    gg = np.zeros((n,));
    rr = np.zeros((n,));

    #forward sweeping
    gg[0] = g[0]/f[0];

    for i in range(1,n-1):
        gg[i] = g[i]/(f[i]-e[i]*gg[i-1]);

    rr[0] = r[0]/f[0];
    for i in range(1,n):
        rr[i] = (r[i]-e[i]*rr[i-1])/(f[i]-e[i]*gg[i-1]);

    # back substitution
    X = np.zeros((n,));
    X[n-1] = rr[n-1];
    for i in range(n-2,-1,-1):
        X[i] = rr[i] - gg[i]*X[i+1];

    return X;

In [7]:
e = np.array([0,-1,-1,-1])
f = np.array([2.04, 2.04, 2.04, 2.04])
g = np.array([-1,-1,-1,0])
r = np.array([40.8, 0.8, 0.8, 200.8])

x= triDiagonal(e,f,g,r)

print(x)

[ 65.96983437  93.77846211 124.53822833 159.47952369]
