<a href="https://colab.research.google.com/github/hamidrezanorouzi/numericalMethods/blob/main/Lectures/linearSystems_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Notes**❕
This content forms a part of the instructional presentations for the **`numerical methods in chemical engineering`** course designed for undergraduate chemical engineering students at Amirkabir University of Technology.

Feel free to utilize the information and source codes provided in this material, ensuring appropriate acknowledgment of the original document.

The visual elements featured in this document have been sourced from the following origins, unless specified otherwise:

* Steven C. Chapra, Applied Numerical Methods with Matlab for Engineers and Scientists, 3rd edition, McGraw-Hill (2012).


<div align="center">
🟧 🟧 🟧
</dive>

---

# 🔴 1) Where do we face solving a set of linear equations?

* **Chemical Systems (Tens to Thousands of Equations):** M&E balances are employed in diverse chemical systems such as distillation columns, adsorption columns, and chemical processes. These systems often entail solving systems of equations ranging from tens to thousands, reflecting the intricate interplay of chemical reactions and mass/energy transfers.

* **Reactor Engineering (Tens of Equations):** Reactor engineering deals with systems characterized by numerous elementary reactions. Typically, tens of equations are formulated to describe reaction kinetics and species concentrations within the reactor.

* **Curve Fitting (Usually Less than 10 Equations):** Curve fitting scenarios involve the determination of linear systems, typically containing fewer than ten equations. These are essential for fitting experimental data to mathematical models or functions.

* **Solving ODEs and PDEs (Thousands to Millions of Equations):** Solving ordinary differential equations (ODEs) and partial differential equations (PDEs), often encountered in boundary value problems, necessitates techniques like linearization and discretization. These processes transform complex continuous problems into sets of linear equations that may range from thousands to millions in scale.


# 🟢 2) Gauss elimination

## 2-1) Gauss elimination without pivoting

* Consider the following set of equations:
$$
[A]{x} = {B}
$$
 where [A] is the matrix of coefficient and B is the vector of known variables and $x$ is the vector of unknowns.
* Gauss elminination is based on the operations (on rows of the system) to convert the coefficient matrix into a upper-triangle matrix.
$$
[U]{x} = {B^{'}}
$$

* Then using back-substitution from the last equation to obtain the solution of the system.

<div align="center">
<img src="https://drive.google.com/uc?id=1f2csAYPmDogI2vuas9KbmJ7JOyo6GcHq" width = "400">
</div>

### Rules of for triangulation:

* Any equation can be multiplied by a nonzero scalar without affecting the solution.
* Any equation can be added to (or subtracted from) another equation without affecting the solution.
* Any two equations can interchange positions within the set without affecting the solution.


### ❓ **Example 1:**
Solve the following system of equations using gauss elimination.

$$
3x_1 +18 x_2+ 9x_3= 18\\
2x_1 +3 x_2 +3 x_3=117\\
4x_1 +1 x_2 +2 x_3=283
$$

&nbsp;


💡 *Solution*


The above set in matrix form becomes:
$$ \begin{bmatrix}
3 & 18 & 9 \\
2 & 3 & 3 \\
4 & 1 & 2
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3\end{bmatrix} =
\begin{bmatrix} 18 \\ 117\\ 283 \end{bmatrix}
$$

**Step 1:** Write the augmented matrix:


\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
2 & 3 & 3 & 117 \\
4 & 1 & 2 & 283 \\
\end{array}

**Step 2:** $a_{1,1}$ is chosen as pivot element to make elements under the pivot element zero:

1) Row2 - (2/3) * Row1 → Row2

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
4 & 1 & 2 & 283 \\
\end{array}

2) Row3 - (4/3) * Row1 → Row3

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
0 & -23 & -10 & 259 \\
\end{array}



**Step 3:** $a_{2,2}$ is chosen as pivot element to make elements under the pivot element zero:

1) Row3 - (23/7) * Row2 → Row3

\begin{array}{ccc|c}
3 & 18 & 9 & 18 \\
0 & -9 & -3 & 105 \\
0 &  0 & \frac{-7}{3} & \frac{-28}{3} \\
\end{array}



**Step 4:** Back substitution:

&nbsp;

$$
3x_1+18x_2+9x_3 = 18 \\
-9x_2 - 3x_3 = 105 \\
-\frac{7}{3}x_3 = \frac{-28}{3}
$$

&nbsp;


$$
x_3 = 4,  x_2 = -13, x_1 = 117
$$

## 2-2) Code for Gauss elimination without pivoting

In [ ]:
import numpy as np

def gaussEliminationNoPivoting(A, B):

  n = len(A)
  augMat = np.concatenate([A,B],1)

  # forward pass
  for k in range(n-1):

    # making elements below the pivot element zero
    for m in range(k+1,n):
      augMat[m,:] -= (augMat[m,k]/augMat[k,k]) * augMat[k,:]

  # back substitution
  x = np.zeros((n,1))
  x[n-1] = augMat[n-1,n]/augMat[n-1,n-1]

  for k in range(n-2, -1, -1):
    x[k] = (augMat[k,n] - np.dot(augMat[k,k+1:n],x[k+1:n]) )/augMat[k,k]

  return x

In [ ]:
A = np.array([[3.0, 18 , 9],[2,3,3],[4,1,2]]);
B = np.array([[18, 117, 283]]).T

x = gaussEliminationNoPivoting(A,B)
print(x)

[[ 72.]
 [-13.]
 [  4.]]


## 2-3) Gauss elimination with partial pivoting
* Consider the following system of equations:
  
\begin{cases}
2x_2 + 5x_3 = 10\\
x_1+ 3x_2 - x_3 = 4\\
3x_1+x_2+x_3 = -2
\end{cases}

* This will give the following form:

$$ \begin{bmatrix}
0 & 2 & 5 \\
1 & 3 & -1 \\
3 & 1 & 1
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3\end{bmatrix} =
\begin{bmatrix} 10 \\ 4\\ -2 \end{bmatrix}
$$


* In each step, before eliminating the elements below the pivot element, it is advantageous to determine the coefficient with the **largest absolute value** in the column **below the pivot element**. The rows can then be **switched** so that the largest element is the pivot element.

* By rearranging rows of the augmented matrix we can obtain a diagonal dominant matrix (partial pivoting).

 * This reduces the possibility of division by zero.

 * Increases the accuracy of calculation by dividing the elements by larger values (decreasing round-off error).


* Lets consider the following system of two equations. The exact solution is $x_1 = 1/3$ and $x_2 = 2/3$
* Now lets test the solution of Gauss elemination without pivoting:

In [ ]:
A = np.array([[3.0e-12, 3.0],[1.0,1.0]]);
B = np.array([[2.000000000001, 1]]).T

x = gaussEliminationNoPivoting(A,B)
print("Answer is \n",x)

Answer is 
 [[0.33336297]
 [0.66666667]]


## 2-4) Code for Gauss elimination with pivoting


In [ ]:
import numpy as np

def gaussElimination(A, B):
  tol = 0.000001
  #number of rows and columns
  nr,nc = A.shape;
  if nr!=nc:
    print('input matrix A is not square!')
    return None

  #number of equations in the set
  n,m = B.shape
  if n!= nr:
    print('A and B size mismatch')
    return None

  Aug = np.concatenate([A,B],1);
  detA = 1;

  #main loop
  for k in range(n-1):

    #first: partial pivoting
    pElement = abs(Aug[k,k])
    pRow = k;

    #locate maximum  element in the rows below the pElement
    for row in range(k+1,n):
      if abs(Aug[row,k]) > pElement:
        pElement = abs(Aug[row,k])
        pRow = row


    #interchanges the rows, if necessary
    if pRow != k:
      temp = np.array(Aug[k,:])
      Aug[k,:] = Aug[pRow,:]
      Aug[pRow,:] = temp
      detA = -detA  #change of sign


    if abs(Aug[k,k]) < tol:
      print('Singular matrix!')
      return None


    # making elements below the pivot element zero
    for m in range(k+1,n):
      Aug[m,:] -= Aug[m,k]/Aug[k,k] * Aug[k,:]

  #the last equation never checked
  if abs(Aug[n-1,n-1]) < tol:
    print('Singular matrix!')
    return None

  # back substitution
  x = np.zeros((n,1))
  x[n-1] = Aug[n-1,n]/Aug[n-1,n-1];
  detA = detA*Aug[n-1,n-1];

  for k in range(n-2, -1, -1):
    x[k] = (Aug[k,n] - np.dot(Aug[k,k+1:n],x[k+1:n]) )/Aug[k,k]
    detA = detA * Aug[k,k]

  return x, detA;

In [ ]:
A = np.array([[3.0e-12, 3.0],[1.0,1.0]]);
B = np.array([[2.00000000001, 1]]).T

x, det = gaussElimination(A,B)
print("Answer is \n",x)

Answer is 
 [[0.33333333]
 [0.66666667]]
