<a href="https://colab.research.google.com/github/hamidrezanorouzi/numericalMethods/blob/main/Lectures/numPy_GettingStarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to NumPy

NumPy is a Python library that stands for "Numerical Python." It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

To get started with NumPy, you need to import it:

```python
import numpy as np
```


# 2. Creating NumPy Arrays

### Creating 1D and 2D Arrays:

In [1]:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Creating Arrays with Zeros and Ones:


In [2]:
# Creating a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))

# Creating a 2x4 array filled with ones
ones_array = np.ones((2, 4))

### Creating Arrays with a Range of Values:

In [5]:
# Creating an array from 0 to 8 with a step of 2
range_array = np.arange(0, 10, 2)
print("range_array is:", range_array)

# Creating array of values equally spaced
lin = np.linspace(0.0, 10.0, 21)
print("lin is:", lin)

range_array is: [0 2 4 6 8]
lin is: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


### Creating Random Arrays:


In [6]:
# Creating a 3x3 matrix of random values between 0 and 1
random_array = np.random.rand(3, 3)
print(random_array)

[[0.27381072 0.66806182 0.18436933]
 [0.64857279 0.47824298 0.70632653]
 [0.83283609 0.42210995 0.23475899]]


# 3. Basic Operations with NumPy Arrays
### Element-wise Arithmetic Operations:


In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
addition = a + b
print("addition : ", addition)

# Subtraction
subtraction = a - b
print("subtraction : ", subtraction)

# Multiplication
multiplication = a * b
print("multiplication : ", multiplication)


# Division
division = a / b
print("division : ", division)

addition :  [5 7 9]
subtraction :  [-3 -3 -3]
multiplication :  [ 4 10 18]
division :  [0.25 0.4  0.5 ]


### Element-wise Operations:


In [9]:
# Square each element
square = np.square(a)
print("square: ", square)
# Square root of each element
sqrt = np.sqrt(a)
print("sqrt: ", sqrt)

square:  [1 4 9]
sqrt:  [1.         1.41421356 1.73205081]


### More Functions:

NumPy provides a wide range of mathematical functions for arrays. Here are a few examples:

- `np.exp(arr)`: Compute the exponent of each element.
- `np.log(arr)`: Compute the natural logarithm of each element.
- `np.sin(arr)`, `np.cos(arr)`, `np.tan(arr)`: Compute trigonometric functions element-wise.

# 4. Matrix Manipulation
### Transpose a Matrix and Matrix Multiplication (Dot Product)

In [11]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Transpose of a matrix
transposed_matrix_a = matrix_a.T
print(transposed_matrix_a)

# Matrix multiplication
result = np.dot(matrix_a, matrix_b)
print("result \n", result)

[[1 3]
 [2 4]]
result 
 [[19 22]
 [43 50]]


### Matrix Inversion and determinant

In [12]:
# Inverse of a matrix
inverse_matrix = np.linalg.inv(matrix_a)

# Determinant of a matrix
determinant = np.linalg.det(matrix_a)

# 5. Linear Algebra Operations
### Solving a Linear System of Equations:


In [14]:
A = np.array([[2, 3], [1, -2]])
b = np.array([5, 1])

# Solve Ax = b for x
x = np.linalg.solve(A, b)
print("solution is ", x)

solution is  [1.85714286 0.42857143]


# 6. Additional NumPy Features

In [21]:
# Broadcasting a scalar to an array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
result = arr_1d + 2  # Adding 2 to each element using

# Compute statistics on arrays
total = np.sum(arr_1d)
average = np.mean(arr_1d)
maximum = np.max(arr_1d)
minimum = np.min(arr_1d)

# Reshaping an array
reshaped = np.reshape(arr_1d, (3, 2))
reshaped_vec = np.reshape(np.array([10, 11, 12]), (3,1))
print(reshaped)
print(reshaped_vec)
# Concatenating arrays
concatenated = np.concatenate((reshaped,reshaped_vec),axis=1)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]
[[10]
 [11]
 [12]]
[[ 1  2 10]
 [ 3  4 11]
 [ 5  6 12]]
